parameters:

services:
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'

    App\Domain\Episode\Service\:
        resource: '../src/Domain/Episode/Service/'
        public: true

    App\Domain\Review\Service\:
        resource: '../src/Domain/Review/Service/'
        public: true

    Sentiment\Analyzer: ~
    App\Infrastructure\SentimentAnalyzer\:
        resource: '../src/Infrastructure/SentimentAnalyzer/'
        arguments:
            $analyzer: '@Sentiment\Analyzer'
        public: true

when@test:
    services:
        _defaults:
            autowire: true # Automatically injects dependencies in your services.
            autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        App\Tests\Builder\:
            resource: '../tests/Builder/'
            public: true
