name: test-task

services:
  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${COMPOSE_PROJECT_NAME}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --lc-collate=ru_RU.UTF-8 --lc-ctype=ru_RU.UTF-8
    ports:
      - target: 5432
        published: 5432

  php-cli:
    container_name: ${COMPOSE_PROJECT_NAME}-php-cli
    user: "1000:1000"
    build:
      context: ./../
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./../app/
        target: /var/www/html/
    env_file: ./../app/.env.test

  composer:
    container_name: ${COMPOSE_PROJECT_NAME}-composer
    image: composer:2.6.6
    command: [install, --ignore-platform-reqs]
    volumes:
      - type: bind
        source: ./../app/
        target: /app

